title: 'Structured Science'
description: 'Tools, templates, tips & tricks for organized science.'

remote_theme: hydecorp/hydejack

favicon: ''

author:
  social:
    github: StructuredScience
    twitter: TomDonoghue
